# Generated by Django 4.2.6 on 2023-10-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purecodes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
